import type { Question } from '@/types/quiz'

// PDF 기출문제: 소방설비기사(전기분야) 2019~2025년 기출

export const PDF_QUESTIONS: Question[] = [
  {
    id: 'p001',
    source: '2019.03 기출 #16',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '연면적이 1000m2 이상인목조건축물은그외벽 ^ 및 처마 밑의 연소할 우려가 있는 부분을 방화구조 \'-9-8-.1-0-.문- 0-5\' 로 하여야 하는데 이때 연소우려가 있는 부분은? （단, 동일한 대지 안에 2동 이상의 건물이 있는 경우이며, 공원 • 광장 • 하천의 공지나 수면 또는 내화구조의 벽, 기타 이와 유사한 것에 접하는 부분 을 제외한다.）',
    choices: [
      { id: 1, text: '상호의 외벽 간 중심선으로부터 1층은 3m' },
      { id: 2, text: '상호의 외벽 간 중심선으로부터 2층은 7m' },
      { id: 3, text: '상호의 외벽 간 중심선으로부터 3층은 11m' },
      { id: 4, text: '상호의 외벽 간 중심선으로부터 4층은 13m' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p002',
    source: '2019.03 기출 #43',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '화재의 예방 및 안전관리에 관한 법령상 화재안전 조사위원회의 위원에 해당하지 아니하는 사람은?',
    choices: [
      { id: 1, text: '소방기술사' },
      { id: 2, text: '소방시설관리사' },
      { id: 3, text: '소방 관련 분야의 석사학위 이상을 취득한' },
      { id: 4, text: '소방 관련 법인 또는 단체에서 소방 관련 업' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p003',
    source: '2019.03 기출 #57',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '화재가 발생하는 경우 인명 또는 재산의 피해가 1 클 것으로 예상되는 때 소방대상물의 개수 • 이 , 전 • 제거, 사용금지 등의 필요한 조치를 명할 수 있는 자는?',
    choices: [
      { id: 1, text: '시 • 도지사' },
      { id: 2, text: '의용소방대장' },
      { id: 3, text: '기초자치단체장' },
      { id: 4, text: '소방청장, 소방본부장 또는 소방서장' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p004',
    source: '2019.03 기출 #59',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '특정소방대상물의 관계인이 소방안전관리자를 해 p 6.1（여 541임한 경우 재선임을 해야 하는 기준은? （단, 해임 」싸쁴한 날부터를 기준일로 한다.）',
    choices: [
      { id: 1, text: '15층인 특정소방대상물（아트는 제외）' },
      { id: 2, text: '가연성 가스를 2000톤 저장 • 취급하는 시설' },
      { id: 3, text: '21층인 아트로서 300세대인 것 _ 30층 이상' },
      { id: 4, text: '연면적 20000m2인 문화 • 집회 및 운동시설' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p005',
    source: '2019.03 기출 #61',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '정온식 감지선형 감지기에 관한 설명으로 옳은 | 09.05.문씨 것은?',
    choices: [
      { id: 1, text: '보상식 스포트형 감지기 또는 열복합형 감지기' },
      { id: 2, text: '정온식 감지선형 감지기' },
      { id: 3, text: '차동식 스포트형 감지기' },
      { id: 4, text: '그 주위온도가 일정한 온도상승률 이상이' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p006',
    source: '2019.03 기출 #70',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '비상경보설비를 설치하여야 할 특정소방대상물 로 옳은 것은?（단, 지하구, 모래 • 석재 등 불연 （） 설은 제외한다.）',
    choices: [
      { id: 1, text: '터널로서 길이가 400m 이상인 것' },
      { id: 2, text: '30명 ■— 50명' },
      { id: 3, text: '지하층 또는 무창층의 바닥면적이 150m2（공' },
      { id: 4, text: '연면적 300m2（사람이 거주하지 않거나 벽이' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p007',
    source: '2019.03 기출 #79',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '자가발전설비, 비상전원수전설비, 축전지설비 또 는 전기저장장치(외부 전기에너지를 저장해 두 -------었다가 필요한 때 전기를 공급하는 장치)를 비상 콘센트설비의 비상전원으로 설치하여야 하는 특 정소방대상물로 옳은 것은?',
    choices: [
      { id: 1, text: '지하층을 제외한 층수가 4층 이상으로서 연' },
      { id: 2, text: '지하층을 제외한 층수가 5층 이상으로서 연' },
      { id: 3, text: '지하층을 제외한 층수가 6층 이상으로서 연' },
      { id: 4, text: '지하층을 제외한 층수가 7층 이상으로서 연' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p008',
    source: '2019.04 기출 #1',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '1 5 5 . . 0 0 3 5. . 문 문 4 51 2 ③ 과염소산 퍼 위험물령〔별표 13 위험물 유 별 성 질 품 명 •아염소산염륜 •염소산염류 •과염소산염류 산화성 • 질산염류 제 1류 고체 •무기과산화물 11산고（일산GQ）, …염 류, 무기과산화물 •황화인 •적린 •활 가연성 제?류 • 마그네슘 고체 •금속분 f QO 2황화적황마 •황린 •칼륨 자연발화성 •나트륨 물질 및 제 3류 •트리에틸알루미늄 금수성 • 금속의 수소화물_________ 물질 J 황칼나트알 ] 19-40 • HR',
    choices: [
      { id: 1, text: '소방활동구역 안에 있는 소방대상물의 소유' },
      { id: 2, text: '전기 • 가스 • 수도 • 통신 • 교통의 업무에 종' },
      { id: 3, text: '부동산업자는 관계인이 아니므로 해당 없음' },
      { id: 4, text: '취재인력 등 보도업무에 종사하는 자' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p009',
    source: '2019.04 기출 #4',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: ': 베이스전류〔⑴八〕 IE : 이미터전류〔mA〕 이미터접지 전류증폭률 乃는 • 분자, 분모의 단위만 일치시켜 주면 mA — A로 환산하지 않아도 된다. 그래도 의심되면 mA — A로 환산하자. 값은 동일하게 나온다. 乃 그 -- I - c - — --- 0 -- .9 -- 8 - X -- 1 - 0 - ^ -三丁 49 IetLj (1 — 0.98)x10* Jama................... 베이스접지 전류증폭률 “i으 여기서, a： 베이스접지 전류증폭률 月 : 이미터접지 전류증폭률 • 이상적인 트랜지스터의 베이스접지 전류증폭 률 a 는 1이다. • 전류증폭률전류증폭정수 • 베이스접지 베이스접지 증폭기 \'紀兪含',
    choices: [
      { id: 1, text: '물에 의한 봉상주수' },
      { id: 2, text: '물에 의한 적상주수' },
      { id: 3, text: '물에 의한 무상주수' },
      { id: 4, text: '어떤 상태의 주수에 의해서도 효과가 없다.' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p010',
    source: '2019.04 기출 #15',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '도장작업 공정에서의 위험도를 설명한 것으로 틀린 것은?',
    choices: [
      { id: 1, text: '도장작업 그 자체 못지않게 건조공정도 위험' },
      { id: 2, text: '인화성 용제가 쓰이지 않으므로 폭발의 위험이' },
      { id: 3, text: '도장작업장은 폭발시를 대비하여 지붕을 시' },
      { id: 4, text: '도장실의 환기덕트를 주기적으로 청소하여' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p011',
    source: '2019.04 기출 #37',
    difficulty: 3,
    subject: 2,
    subjectName: '소방전기일반',
    stem: '교류전력변환장치로 사용되는 인버터회로에 대 헤^한 설명으로 옳지 않은 것은? 효04.05시.문 23① 직류전력을 교류전력으로 변환하는 장치를 인버터라고 한다.',
    choices: [
      { id: 1, text: '다이오드를 직렬로 추가한다.' },
      { id: 2, text: '다이오드를 병렬로 추가한다.' },
      { id: 3, text: '다이오드의 양단에 적당한 값의 저항을 추' },
      { id: 4, text: '다이오드의 양단에 적당한 값의 콘덴서를' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p012',
    source: '2019.04 기출 #46',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '소방대라 함은 화재를 진압하고 화재, 재난 • 재 구성원으로 틀린 것은?',
    choices: [
      { id: 1, text: '소방공무원' },
      { id: 2, text: '소방안전관리원' },
      { id: 3, text: '의무소방원' },
      { id: 4, text: '의용소방대원' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p013',
    source: '2019.04 기출 #71',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '비상경보설비의 축전지설비의 구조에 대한 설명 으로 틀린 것은?',
    choices: [
      { id: 1, text: '예비전원을 병렬로 접속하는 경우에는 역충' },
      { id: 2, text: '내부에 주전원의 양극을 동시에 개폐할 수' },
      { id: 3, text: '교류전류 一 직류전류' },
      { id: 4, text: '예비전원은 축전지설비용 예비전원과 외부 [1' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p014',
    source: '2019.04 기출 #73',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '부착높이 3m, 바닥면적 50m2인 주요구조부를 내 최소 설치개수는?',
    choices: [
      { id: 1, text: '제연설비가 작동한 때' },
      { id: 2, text: '자동소화설비가 작동한 때' },
      { id: 3, text: '비상경보설비의 발신기가 작동한 때' },
      { id: 4, text: '자동화재탐지설비의 감지기가 작동한 때' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p015',
    source: '2019.09 기출 #1',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '3 5 . . 0 0 6 9. . 문 문 6 67 3 ） 비상방송설비에는 그 설비에 대한 감시상태 를(@)분간지속한후유효하게 (©)분이 상 경보할 수 있는 축전지설비(수신기에 내장 하는 경우를 포함)를 설치하여야 한다.',
    choices: [
      { id: 1, text: '한국소방산업기술원의 업무' },
      { id: 2, text: '소방헬리콥터 및 소방정' },
      { id: 3, text: '소화용수설비 및 피난구조설비' },
      { id: 4, text: '방화복 등 소방활동에 필요한 소방장비' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p016',
    source: '2019.09 기출 #16',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '화재의 유형별 특성에 관한 설명으로 옳은 것은? 찌 7]① A급 화재는 무색으로 표시하며, 감전의 위 험이 있으므로 주수소화를 엄금한다.',
    choices: [
      { id: 1, text: '무색 ~ 백색, 감전의 위험이 있으므로 주수소화' },
      { id: 2, text: '가연성 가스' },
      { id: 3, text: '백색 — 청색, 가연성이 강한 금속의 화재 — 전' },
      { id: 4, text: '청색 一 무색, 연소 후에 재를 남긴다. 一 가연성' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p017',
    source: '2019.09 기출 #45',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '항공기격납고는 특정소방대상물 중 어 시설에 | | 해당하는가?',
    choices: [
      { id: 1, text: '위험물 저장 및 처리 시설' },
      { id: 2, text: '항공기 및 자동차관련 시설' },
      { id: 3, text: '창고시설' },
      { id: 4, text: '업무시설' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p018',
    source: '2019.09 기출 #46',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '위험물안전관리법령상 제조소 등의 관계인은 위 험물의 안전관리에 관한 직무를 수행하게 하기 위 16.03 문 55 하여 제조소 등마다 위험물의 취급에 관한 자격이 이 경우 제조소 등의 관계인이 지켜야 할 기준으 로 틀린 것은?',
    choices: [
      { id: 1, text: '15일 이내 一 30일 이내' },
      { id: 2, text: '제조소 등의 관계인이 안전관리자를 선임한' },
      { id: 3, text: '제조소 등의 관계인은 안전관리자가 여행 •' },
      { id: 4, text: '안전관리자는 위험물을 취급하는 작업을 하는' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p019',
    source: '2020.06 기출 #1',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '•유류탱크에서 탱크바닥에 물과 기 보일오버 름의 에멀션이 섞여 있을 때 이로 인 (Boil over) 하여 화재가 발생하는 현상 •연소유면으로부터 100℃ 이상의 열 가 탱크 저부에 고여 있는 물을 비등하게 하면서 연소유를 탱크 밖 으로 비산시키며 연소하는 현상 • 저장탱크에 저장된 유류저장량이 내 오일오버 용적의 50% 이하로 충전되어 있을 (Oil over) 때 화재로 인하여 탱크가 폭발하는 현상 •물이 점성의 뜨거운 기름표면 아래 프로스오버 에서 끓을 때 화재를 수반하지 않고 (Froth over) 용기가 넘치는 현상 • 유류탱크 화재시 기름 표면에 물을 살수하면 기름이 탱크 밖으로 비산 하여 화재가 확대되는 현상(연소유 가 비사되어 타크 외부까지 화재가 확산) • 물이 연소유의 뜨거운 표면에 들어 갈 때 기름 표면에서 화재가 발생하 는 현상 쎄 슬롭오버 • 2화줘로 소화하기 위한 물이 수분의 (Slop over) 급격한 증발에 의하여 액면이 거품을 일으키면서 열유층 밑의 냉유가 급히 열팽창하여 기름의 일부가 불이 붙은 채 탱크벽을 넘어서 일출하는 현상 • 연소면의 온도가 100℃ 이상일 때 물 을 주수하면 발생 • 소화시 외부에서 방사하는 포에 의해 발생 유 會1',
    choices: [
      { id: 1, text: '급강하 一 상승' },
      { id: 2, text: '산소가 감소된다. 1' },
      { id: 3, text: '일산화탄소가 증가한다.' },
      { id: 4, text: '이산화탄소가 증가한다.' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p020',
    source: '2020.06 기출 #52',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '화재의 예방 및 안전관리에 관한 법령상 정당한 사유 없이 화재의 예방조치에 관한 명령에 따르 지 아니한 경우에 대한 벌칙은?',
    choices: [
      { id: 1, text: '100만원 이하의 벌금' },
      { id: 2, text: '200만원 이하의 벌금' },
      { id: 3, text: '300만원 이하의 벌금' },
      { id: 4, text: '500만원 이하의 벌금' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p021',
    source: '2020.06 기출 #71',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '비상콘센트설비의 화재안전기준에 따른 비상콘센 트의 시설기준에 적합하지 않은 것은?',
    choices: [
      { id: 1, text: '0.8~ 1.5m 이하이므로 1.45m는 적합' },
      { id: 2, text: '1000m2 미만은 계단 출입구로부터 5m 이내에' },
      { id: 3, text: '3000m2 이상의 지하상가는 수평거리 25m 이' },
      { id: 4, text: '바닥면적의 합계가 2500m2인 지하층의 수' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p022',
    source: '2020.06 기출 #75',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '비상경보설비의 구성요소로 옳은 것은?',
    choices: [
      { id: 1, text: '기동장치, 경종, 화재표시등, 전원, 감지기' },
      { id: 2, text: '전원, 경종, 기동장치, 위치표시등' },
      { id: 3, text: '위치표시등, 경종, 화재표시등, 전원, 감지기' },
      { id: 4, text: '경종, 기동장치, 화재표시등, 위치표시등,' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p023',
    source: '2020.08 기출 #1',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '2020년 기사 제4회 필기시험 ! 자격 종목 종목코드 죠설비기사(전기분야) 으 각 문항은 4지택일형으로 질문에 가장 적합한 보기 항을 선택하여 제 1 과목 소방원론 |17 아 피난시 하나의 수단이 고장 등으로 사용이 불가능 하더라도 다른 수단 및 방법을 통해서 피난할 수 있도록 하는 것으로 2방향 이상의 피난통로를 확 보하는 피난대책의 일반원칙은?',
    choices: [
      { id: 1, text: '복합건축물로서 연면적 3500m2 이상인 경' },
      { id: 2, text: '창고시설（물류터미널은 제외）로서 바닥면적' },
      { id: 3, text: '숙박이 가능한 수련시설 용도로 사용되는' },
      { id: 4, text: '판매시설, 운수시설 및 창고시설（물류터미' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p024',
    source: '2020.08 기출 #3',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '제1 인산암모늄 ABC 차고 • 주차 종 (NH4H2Po4) 담홍색 급 장에 적합 제 중탄산칼륨 4 + 요소 종 회 (백)색 BC 급 — (KHCO3 + (NH2)2CO) 야? 공기 중의 산소의 농도는 약 몇 v이%인가? 6.03.문191 ① 10 ② 13 (3) 17 ④ 21',
    choices: [
      { id: 1, text: '건축물, 지하가, 터널 또는 공동구의 출입구' },
      { id: 2, text: '다른 용도로 사용되는 안테나로 인한 통신장' },
      { id: 3, text: '옥외안테나 一 무선통신보조설비 안테나' },
      { id: 4, text: '수신기가 설치된 장소 등 사람이 상시 근' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p025',
    source: '2020.08 기출 #4',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: ': △결선시 전류〔A〕 q슥*恩*_______________________________ 기동전류 | 소비전력 | 기동토크 “ Y-△기동방식 _ 1 _______________ 직입기동방식 흐________________ 宗 3상 유도전동기의 기동시 직입기동방식을 Y—A 기동방식으로 변경하면 기동전류, 소비전력, 기 동토크가 모두 ｛로 감소한다. 그림의 시퀀스회로와 등가인 논리게이트는?',
    choices: [
      { id: 1, text: 'OR게이트' },
      { id: 2, text: 'AND게이트' },
      { id: 3, text: 'NOT게이트' },
      { id: 4, text: 'NOR게이트' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p026',
    source: '2020.08 기출 #6',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '공기 중에서 수소의 연소범위로 옳은 것은? ① 0.4〜4vo1% ()③ 4〜75vol%',
    choices: [
      { id: 1, text: '의료법에 의한 종합병원에 있어서는 30m' },
      { id: 2, text: '도시가스사업법에 의한 가스공급시설에 있' },
      { id: 3, text: '사용전압 35000V를 초과하는 특고압가공전' },
      { id: 4, text: '문화유산의 보존 및 활용에 관한 법률과 지' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p027',
    source: '2020.08 기출 #74',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '비상경보설비 및 단독경보형 감지기의 화재안전 기준에 따른 발신기의 시설기준으로 틀린 것은?',
    choices: [
      { id: 1, text: '발신기의 위치표시등은 함의 하부에 설치' },
      { id: 2, text: '조작스위치는 바닥으로부터 0.8m 이상 1.5m' },
      { id: 3, text: '복도 또는 별도로 구획된 실로서 보행거리' },
      { id: 4, text: '특정소방대상물의 층마다 설치하되, 해당' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p028',
    source: '2020.08 기출 #80',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '비상콘센트설비의 성능인증 및 제품검사의 기술 기준에 따라 비상콘센트설비에 사용되는 부품에 대한 설명으로 틀린 것은?',
    choices: [
      { id: 1, text: '진공차단기 一 배선용 차단기' },
      { id: 2, text: '접속기는 KS C 8305（배선용 꽂음 접속기）' },
      { id: 3, text: '표시등의 소켓은 접속이 확실하여야 하며' },
      { id: 4, text: '단자는 충분한 전류용량을 갖는 것으로 하' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p029',
    source: '2020.09 기출 #48',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '위험물안전관리법령상 관계인이 예방규정을 정 I 하여야 하는 위험물을 취급하는 제조소의 지정수 량 기준으로 옳은 것은?',
    choices: [
      { id: 1, text: '지정수량의 10배 이상' },
      { id: 2, text: '지정수량의 100배 이상' },
      { id: 3, text: '지정수량의 150배 이상' },
      { id: 4, text: '지정수량의 200배 이상' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p030',
    source: '2020.09 기출 #52',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '화재의 예방 및 안전관리에 관한 법령상 특수가연 q프延 물의 저장 및 취급기준을 위반한 경우 과태료 부 과기준은?',
    choices: [
      { id: 1, text: '소방용수시설•소화기' },
      { id: 2, text: '불의 사용에 있어서 지켜 200' },
      { id: 3, text: '특수가연물의 저장 및 취' },
      { id: 4, text: '200만원' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p031',
    source: '2020.09 기출 #55',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '화재의 예방 및 안전관리에 관한 법률상 화재예 방강화지구의 지정대상이 아닌 것은? （단, 소방 [13.09■문 56] 화지구로 지정할 필요가 있다고 인정하는 지역 은 제외한다.）',
    choices: [
      { id: 1, text: '시장지역' },
      { id: 2, text: '농촌지역' },
      { id: 3, text: '목조건물이 밀접한 지역' },
      { id: 4, text: '공장 • 창고가 밀집한 지역' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p032',
    source: '2020.09 기출 #59',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '소방시설공사업법상 도급을 받은 자가 제3자에 게 소방시설공사의 시공을 하도급한 경우에 대한 （） 하는 경우는 제외한다.）',
    choices: [
      { id: 1, text: '100만원 이하의 벌금' },
      { id: 2, text: '300만원 이하의 벌금' },
      { id: 3, text: '1년 이하의 징역 또는 1000만원 이하의 벌금' },
      { id: 4, text: '3년 이하의 징역 또는 1500만원 이하의 벌금' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p033',
    source: '2020.09 기출 #60',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '소방시설 설치 및 관리에 관한 법령상 정당한 사 패 유없이 피난시설 방화구획 및 방화시설의 관리에 필요한 조치명령을 위반한 경우 이에 대한 벌칙 기준으로 옳은 것은?',
    choices: [
      { id: 1, text: '200만원 이하의 벌금' },
      { id: 2, text: '300만원 이하의 벌금 p' },
      { id: 3, text: '1년 이하의 징역 또는 1000만원 이하의 벌금' },
      { id: 4, text: '3년 이하의 징역 또는 3000만원 이하의 벌금' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p034',
    source: '2020.09 기출 #66',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '자동화재탐지설비 및 시각경보장치의 화재안전 灰^] 기주에 따른 자동화재탐지설비의 중계기의 시설 기준으로 틀린 것은?',
    choices: [
      { id: 1, text: '조작 및 점검에 편리하고 화재 및 침수 등의' },
      { id: 2, text: '수신기에서 직접 감지기회로의 도통시험을' },
      { id: 3, text: '감지기 一 수신기, 누전경보기 一 과전류차단기' },
      { id: 4, text: '수신기에 따라 감시되지 아니하는 배선을' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p035',
    source: '2020.09 기출 #75',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '누전경보기의 형식승인 및 제품검사의 기술기준 에 따라 누전경보기에 차단기구를 설치하는 경우 차단기구에 대한 설명으로 틀린 것은?',
    choices: [
      { id: 1, text: '개폐부는 정지점이 명확하여야 한다.' },
      { id: 2, text: '개폐부는 원활하고 확실하게 작동하여야 한다.' },
      { id: 3, text: 'KS C 8321(배선용 차단기) 一 KS C 4613(누전' },
      { id: 4, text: '개폐부는 수동으로 개폐되어야 하며 자동적' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p036',
    source: '2020.09 기출 #76',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '감지기의 형식승인 및 제품검사의 기술기준에 따 른 단독경보형 감지기(주전원이 교류전원 또는 건전지인 것을 포함한다)의 일반기능에 대한 설 명으로 틀린 것은?',
    choices: [
      { id: 1, text: '작동되는 경우 작동표시등에 의하여 화재의' },
      { id: 2, text: '작동되는 경우 내장된 음향장치의 명동에 의' },
      { id: 3, text: '섬광주기는 3초 이내 一 섬광주기는 1초 이내.' },
      { id: 4, text: '자동복귀형 스위치(자동적으로 정위치에 복귀' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p037',
    source: '2020.09 기출 #77',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '자동화재속보설비의 속보기의 성능인증 및 제품 검사의 기술기준에 따라 자동화재속보설비의 속 보기가 소방관서에 자동적으로 통신망을 통해 통 보하는 신호의 내용으로 옳은 것은?',
    choices: [
      { id: 1, text: '당해 소방대상물의 위치 및 규모' },
      { id: 2, text: '당해 소방대상물의 위치 및 용도' },
      { id: 3, text: '당해 화재발생 및 당해 소방대상물의 위치' },
      { id: 4, text: '당해 고장발생 및 당해 소방대상물의 위치' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p038',
    source: '2021.03 기출 #3',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '화재발생시 피난기구로 직접 활용할 수 없는 1 것은?',
    choices: [
      { id: 1, text: '완강기' },
      { id: 2, text: '무선통신보조설비 :소화활동설비' },
      { id: 3, text: '피난사다리' },
      { id: 4, text: '구조대' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p039',
    source: '2021.03 기출 #52',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '화재의 예방 및 안전관리에 관한 법령상 소방안 * 전관리대상물의 소방계획서에 포함되어야 하는 사항이 아닌 것은?',
    choices: [
      { id: 1, text: '소방시설 • 피난시설 및 방화시설의 점검 •' },
      { id: 2, text: '위험물 관련은 해당 없음' },
      { id: 3, text: '특정소방대상물의 근무자 및 거주자의 자위' },
      { id: 4, text: '방화구획, 제연구획, 건축물의 내부 마감재' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p040',
    source: '2021.03 기출 #71',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '누전경보기의 형식승인 및 제품검사의 기술기준 w 耐 에 따라 누전경보기에 사용되는 표시등의 구조 및 기능에 대한 설명으로 틀린 것은?',
    choices: [
      { id: 1, text: '누전등이 설치된 수신부의 지구등은 적색 외' },
      { id: 2, text: '방전등 또는 발광다이오드 제외' },
      { id: 3, text: '주위의 밝기가 300 lx인 장소에서 측정하여' },
      { id: 4, text: '누전등 및 지구등과 쉽게 구별할 수 있도록' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p041',
    source: '2021.03 기출 #72',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '소방시설용 비상전원수전설비의 화재안전기준 [20.09.문 끼 에 따라 일반전기사업자로부터 특고압 또는 고 1 압으로 수전하는 비상전원수전설비로 큐비 클형 을 사용하는 경우의 시설기준으로 틀린 것은? （단, 옥내에 설치하는 경우이다.）',
    choices: [
      { id: 1, text: '외함은 내화성능이 있는 것으로 제작할 것' },
      { id: 2, text: '전용큐비클 또는 공용큐비클식으로 설치할 것' },
      { id: 3, text: '10분 방화문 一 30분 방화문' },
      { id: 4, text: '외함은 두께 2.3mm 이상의 강판과 이와 동' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p042',
    source: '2021.03 기출 #77',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '비상조명등의 형식승인 및 제품검사의 기술기준에 따라 비상조명등의 일반구조로 광원과 전원부를 별도로 수납하는 구조에 대한 설명으로 틀린 것은?',
    choices: [
      { id: 1, text: '방폭구조로 一 불연재료 또는 난연재료의 재질' },
      { id: 2, text: '배선은 충분히 견고한 것을 사용할 것' },
      { id: 3, text: '광원과 전원부 사이의 배선길이는 1m 이하' },
      { id: 4, text: '전원함은 불연재료 또는 난연재료의 재질을' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p043',
    source: '2021.05 기출 #4',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: ': 부하전류〔A〕 cos 6 : 역률 부하측 소비전력 유는 PL 어 4ms6» 3300X33.33X0.8 87991W 88000W 88kW 00c 에서 저항이 10오이고, 저항의 온도계수가 而^ 0.0043인 전선이 있다. 300c에서 이 전선의 저 8-.0-9.-몬- 2-6\' 항은 약 몇 오인가?',
    choices: [
      { id: 1, text: '연기에 의한 시계제한' },
      { id: 2, text: '유독가스에 의한 호흡장애' },
      { id: 3, text: '외부와 단절되어 고립' },
      { id: 4, text: '불연내장재의 사용' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p044',
    source: '2021.05 기출 #7',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '소화약제로 사용되는 이산화탄소에 대한 설명으 스찌로 옳은 것은? 1145.03•문 1 이 효시① 산소와 반응시 흡열반응을 일으킨다. ................ ② 산소와 반응하여 불연성 물질을 발생시킨다.',
    choices: [
      { id: 1, text: '제1종 분말' },
      { id: 2, text: '제2종 분말' },
      { id: 3, text: '제3종 분말' },
      { id: 4, text: '제4종 분말' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p045',
    source: '2021.05 기출 #11',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '위험물안전관리법령상 제6류 위험물을 수납하 는 운반용기의 외부에 주의사항을 표시하여야',
    choices: [
      { id: 1, text: '물기엄금' },
      { id: 2, text: '화기엄금' },
      { id: 3, text: '화기주의 • 충격주의' },
      { id: 4, text: '가연물접촉주의' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p046',
    source: '2021.05 기출 #52',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '소방시설 설치 및 관리에 관한 법령상 시 • 도지 p 7.09.문521사가 소방시설 등의 자체점검을 하지 아니한 관 [ 리업자에게 영업정지를 명할 수 있으나, 이로 인 해 국민에게 심한 불편을 줄 때에는 영업정지 처 분을 갈음하여 과징금 처분을 한다. 과징금의 기 준은?',
    choices: [
      { id: 1, text: '1000만원 이하' },
      { id: 2, text: '2000만원 이하' },
      { id: 3, text: '3000만원 이하' },
      { id: 4, text: '제6류 : 인화성 고체' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p047',
    source: '2021.05 기출 #57',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '화재의 예방 및 안전관리에 관한 법령상 화재안 폐전조사위원회의 위원에 해당하지 아니하는 사 람은?',
    choices: [
      { id: 1, text: '소방기술사' },
      { id: 2, text: '소방시설관리사' },
      { id: 3, text: '소방 관련 분야의 석사학위 이상을 취득한' },
      { id: 4, text: '3년一 5년 [ 0' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p048',
    source: '2021.05 기출 #69',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '유도등 및 유도표지의 화재안전기준에 따른 객 西^ 석유도등의 설치기준이다. 다음（ ）에 들어갈 내용으로 옳은 것은? 0 객석유도등은 객석의（ ）,（ ©）또는 （ ©）에 설치하여야 한다.',
    choices: [
      { id: 1, text: '@ 통로, © 바닥, © 벽' },
      { id: 2, text: '@ 바닥, © 천장, © 벽' },
      { id: 3, text: '© 통로, © 바닥, © 천장' },
      { id: 4, text: '@ 바닥, © 통로, © 출입구' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p049',
    source: '2021.05 기출 #72',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '비상콘센트설비의 성능인증 및 제품검사의 기술 기준에 따른 비상콘센트설비 표시등의 구조 및 기능에 대한 설명으로 틀린 것은?',
    choices: [
      { id: 1, text: '발광다이오드는 제외' },
      { id: 2, text: '소켓은 접속이 확실하여야 하며 쉽게 전구를' },
      { id: 3, text: '적색으로 표시되어야 하며 주위의 밝기가' },
      { id: 4, text: '전구는 사용전압의 130%인 교류전압을 20' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p050',
    source: '2021.05 기출 #77',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '자동화재탐지설비 및 시각경보장치의 화재 안전 어 연기감지기를 설치할 수 없는 건조실 또는 살 균실 등에 적응성 있는 열감지기가 아닌 것은?',
    choices: [
      { id: 1, text: '정온식 1종' },
      { id: 2, text: '정온식 특종' },
      { id: 3, text: '열아날로그식' },
      { id: 4, text: '보상식 스포트형 1종' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p051',
    source: '2021.09 기출 #29',
    difficulty: 3,
    subject: 2,
    subjectName: '소방전기일반',
    stem: '1cm의 간격을 둔 평행 왕복전선에 25A의 전류 1 가 흐른다면 전선 사이에 작용하는 단위길이당 [ ) 힘〔N/m〕은?',
    choices: [
      { id: 1, text: '2.5＞〈10-2N/m(반발력)' },
      { id: 2, text: '1.25〉〈10-2N/m(반발력)' },
      { id: 3, text: '2.5xlO-2N/m(흡인력)' },
      { id: 4, text: '1.25xlO"2N/m(흡인력)' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p052',
    source: '2022.03 기출 #10',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '1 4 5：.：0：5.；문 4시0 기동할 때 전류 오〔A〕의 관계는?',
    choices: [
      { id: 1, text: '비수용성 •一 수용성' },
      { id: 2, text: '무기화합물이다.' },
      { id: 3, text: '불연성 물질이다.' },
      { id: 4, text: '비중은 물보다 무겁다.' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p053',
    source: '2022.03 기출 #21',
    difficulty: 3,
    subject: 2,
    subjectName: '소방전기일반',
    stem: '.05.문 찌기준에 따라 부착높이 8m 이상 15m 미만에 설치 1124 .03.문.； 7；9；66]되는 감지기의 종류로 틀린 것은?',
    choices: [
      { id: 1, text: '불꽃감지기' },
      { id: 2, text: '이온화식 2종' },
      { id: 3, text: '차동식 분포형' },
      { id: 4, text: '보상식 스포트형' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p054',
    source: '2022.03 기출 #47',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '소방시설공사업 법령상 소방시설업자가 소방시 1설공사 등을 맡긴 특정소방대상물의 관계인에게 1 지체 없이 그 사실을 알려야 하는 경우가 아닌 것은?',
    choices: [
      { id: 1, text: '소방시설업자의 지위를 승계한 경우' },
      { id: 2, text: '소방시설업의 등록취소처분 또는 영업정지' },
      { id: 3, text: '휴업하거나 폐업한 경우' },
      { id: 4, text: '소방시설업의 주소지가 변경된 경우' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p055',
    source: '2022.03 기출 #53',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '소방시설공사업 법령상 소방공사감리 업을 등록 H 야.문씨한 자가 수행하여야 할 업무가 아닌 것은?',
    choices: [
      { id: 1, text: '완공된 소방시설 등의 성능시험' },
      { id: 2, text: '소방시설 등 설계변경사항의 적합성 검토' },
      { id: 3, text: '소방시설 등의 설치계획표의 적법성 검토' },
      { id: 4, text: '소방용품 형식승인 및 제품검사의 기술기준' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p056',
    source: '2022.03 기출 #58',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '위험물안전관리법령상 제조소 등의 관계인은 위 격이 있는 자를 위험물안전관리자로 선임하여야 한다. 이 경우 제조소 등의 관계인이 지켜야 할 기준으로 틀린 것은?',
    choices: [
      { id: 1, text: '제조소 등의 관계인은 안전관리자를 해임하' },
      { id: 2, text: '제조소 등의 관계인이 안전관리자를 선임한' },
      { id: 3, text: '제조소 등의 관계인은 안전관리자가 여행 •' },
      { id: 4, text: '안전관리자는 위험물을 취급하는 작업을 하는' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p057',
    source: '2022.03 기출 #70',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '자동화재탐지설비 및 시각경보장치의 화재안전 기준에 따라 전화기기실, 통신기기실 등과 같은 훈소화재의 우려가 있는 장소에 적응성이 없는 감지기는?',
    choices: [
      { id: 1, text: '광전식 스포트형' },
      { id: 2, text: '광전아날로그식 분리형' },
      { id: 3, text: '광전아날로그식 스포트형' },
      { id: 4, text: '이온아날로그식 스포트형' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p058',
    source: '2022.04 기출 #61',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '소방시설용 비상전원수전설비의 화재안전기준 [스히 에 따라 저압으로 수전하는 제1종 배전반 및 분전 반의 외함 두께와 전면판(또는 문) 두께에 대한 설치기준으로 옳은 것은?',
    choices: [
      { id: 1, text: '외함 : 1.0mm 이상, 전면판(또는 문) : 1.2mm' },
      { id: 2, text: '외함 : 1.2mm 이상, 전면판(또는 문) : 1.5mm' },
      { id: 3, text: '외함 : 1.5mm 이상, 전면판(또는 문) : 2.0mm' },
      { id: 4, text: '외함 : 1.6mm 이상, 전면판(또는 문) : 2.3mm' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p059',
    source: '2022.04 기출 #70',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '비상방송설비와 자동화재탐지설비의 연동시 동 작순서로 옳은 것은?',
    choices: [
      { id: 1, text: '기동장치—증폭기 一 수신기 — 조작부—' },
      { id: 2, text: '기동장치 — 조작부 一 증폭기 ― 수신기 一*' },
      { id: 3, text: '기동장치 一 수신기 一 증폭기 一 조작부 一' },
      { id: 4, text: '기동장치 一 증폭기 - 조작부 一 수신기 一' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p060',
    source: '2022.09 기출 #1',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '년 (전기분야) 21—30 ............................... —59 ...............................거 유익사항 ** 인하시기 바랍니다. 합니다. 및 누락 페이지 유무를 확인하시기 바랍니다. 답 1개만을 선택하여야 합니다. 고, 답안카드 작성 시 형별누락, 마킹착오로 인한 불이익은 사항 ** 三---------------------- 실 수 있습니다. 가답안에 대한 의견은 큐넷의 ［가답안 의견 답으로 갈음합니다. 이 있으시면 고객참여(http：//hrdkorea.or.kr/7/1/1)를 통해',
    choices: [
      { id: 1, text: '광축（송광면과 수광면의 중심을 연결한 선）' },
      { id: 2, text: '감지기의 수광면은 햇빛을 직접 받지 않도록' },
      { id: 3, text: '광축의 높이는 천장 등（천장의 실내에 면한' },
      { id: 4, text: '감지기의 송광부와 수광부는 설치된 뒷벽으' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p061',
    source: '2022.09 기출 #4',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: ': 전류의 최대값〔A〕 v(t) 14nsim此 50cos(u)t + a) —c___zr 50sin(W+ 9 + 90°) i(t) 소이110此 4sin(W + 9 + 30°) —T T (2) 무효전력 여기서, Pr : 무효전력〔Var〕 Vm : 전압의 최대값〔V〕 Im : 전류의 최대값〔A〕 e: 각도〔。:। 효 22-67',
    choices: [
      { id: 1, text: '아이오딘화반응을 일으키기 때문이다.' },
      { id: 2, text: '비누화반응을 일으키기 때문이다.' },
      { id: 3, text: '브로민화반응을 일으키기 때문이다.' },
      { id: 4, text: '질화반응을 일으키기 때문이다.' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p062',
    source: '2022.09 기출 #5',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '〜 15W ② 마이크, 증폭기, 확성 이 기를 일체화하여 소 동 형 경량 형 ① 소규모 방송설비에 사용 탁상형 10〜 60W ② 입력장치 : 마이크, 라디오, 사이렌, 카 세트테이프 고 저 0 혀 0',
    choices: [
      { id: 1, text: '복사열은 절대온도의 제곱에 비례한다.' },
      { id: 2, text: '복사열（열복사량）은 복사체의 절대온도의 4제곱' },
      { id: 3, text: '복사열은 절대온도의 제곱에 반비례한다.' },
      { id: 4, text: '복사열은 절대온도의 4제곱에 반비례한다.' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p063',
    source: '2022.09 기출 #6',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '여기서, 6心) : 비례적분(PI)제어 전달함수 k:비례감도 T： 적분시간〔s〕 PI제어 전달함수 仁(日는 * 사 + 三| 三) 쯨 + ! 5|1 + 5( J3s + 1\\ 15s + 5 5hd— 탑③',
    choices: [
      { id: 1, text: '실내에서 가연성 가스가 축적되어 발생되는' },
      { id: 2, text: '실내에서 에너지가 리게 집적되는 현상' },
      { id: 3, text: '실내에서 가연성 가스가 분해되는 현상' },
      { id: 4, text: '실내에서 가연성 가스가 방출되는 현상' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p064',
    source: '2022.09 기출 #21',
    difficulty: 3,
    subject: 2,
    subjectName: '소방전기일반',
    stem: '• 리튬계 2차 축전지 20 •비상조명등 • 알칼리계 2차 축전지 | 보기 @ | •가스누설경보기 • 리튬계 2차 축전지 • 무보수 밀폐형 연축전지 II',
    choices: [
      { id: 1, text: '간헐현상을 제거하기 위한 제어' },
      { id: 2, text: '이득교점 주수가 낮아지며, 대' },
      { id: 3, text: '동작신호의 기울기에 비례한 조' },
      { id: 4, text: '비례적분제어' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p065',
    source: '2022.09 기출 #44',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '화재의 예방 및 안전관리에 관한 법령상 일반음 설치하는 경우 지켜야 하는 상황으로 틀린 것은?',
    choices: [
      { id: 1, text: '열을 발생하는 조리기구는 반자 또는 선반으' },
      { id: 2, text: '주방설비에 부속된 배출덕트는 0.5mm 이상' },
      { id: 3, text: '주방시설에는 동물 또는 식물의 기름을 제거' },
      { id: 4, text: '열을 발생하는 조리기구로부터 0.5m 이내의' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p066',
    source: '2022.09 기출 #61',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '자동화재속보설비의 속보기의 성능인증 및 제품 검사의 기술기준에 따른 속보기의 구조에 대한 설명으로 틀린 것은?',
    choices: [
      { id: 1, text: '예비전원회로에는 단락사고 등을 방지하기' },
      { id: 2, text: '수동통화용 송수화장치를 설치하여야 한다.' },
      { id: 3, text: '화재표시 복구스위치 및 음향장치의 울림을' },
      { id: 4, text: '작동시 그 작동시간과 작동횟수를 표시할 수' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p067',
    source: '2023.03 기출 #1',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '(기본법 56 조) (7) 관계서류 미보관자(공사업법 40 조) (8) 소방기술자 미배치자(공사업법 40 조) (9) 완공검사를 받지 아니한 자(공사업법 40 조) (10) 방염성능기준 미만으로 방염한 자(공사업법 40 조) (11) 하도급 미통지자(공사업법 40 조) (12) 관계인에게 지위승계 • 행정처분 • 휴업 • 폐업 사실을 거짓으로 알린 자(공사업법 40 조) 서 100만원 이하의 벌금 (1) 관계인의 소방활동 미수행(기본법 의조) (2) 픠난명 령 위반(기본법 54 조) | 보가]지 (3) 위험시설 등에 대한 긴급조치 방해(기본법 54 조) (4) 거짓보고 또는 자료 미제출자(공사업법 38 조) 히 관계공무원의 출입 •조사 • 검사 방해(공사업법 38조) [ Sgjf까(착읠프희________________ )',
    choices: [
      { id: 1, text: '한국소방안전원 또는 이와 유사한 명칭을 사' },
      { id: 2, text: '소방활동구역을 대통령령으로 정하는 사람' },
      { id: 3, text: '화재진압 구조 • 구급 활동을 위해 사이렌을' },
      { id: 4, text: '화재, 재난 • 재해, 그 밖의 위급한 상황이' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p068',
    source: '2023.03 기출 #72',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '무선통신보조설비의 화재안전기준에 따른 옥외 西^ 안테나의 설치기준으로 옳지 않은 것은?',
    choices: [
      { id: 1, text: '건축물, 지하가, 터널 또는 공동구의 출입구' },
      { id: 2, text: '다른 용도로 사용되는 안테나로 인한 통신장' },
      { id: 3, text: '“옥외안테나” - “무선통신보조설비 안테나”' },
      { id: 4, text: '수신기가 설치된 장소 등 사람이 상시 근' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p069',
    source: '2023.05 기출 #4',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '다음은 위험물의 정의이다. 다음( )안에알맞 1 은 것은? “윈험물!이라 함은 (0) 또는 발화성 등의 성 질을 가지는 것으로서 ( ©)이 정하는 물품을 [ 말한다. [',
    choices: [
      { id: 1, text: '0 인화성, © 국무총리령' },
      { id: 2, text: 'O 휘발성, © 국무총리령' },
      { id: 3, text: '화재실의뀨' },
      { id: 4, text: '차 혈량 g' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p070',
    source: '2023.05 기출 #24',
    difficulty: 3,
    subject: 2,
    subjectName: '소방전기일반',
    stem: '전자유도현상에서 코일에 생기는 유도기전력의 방향을 정의한 법칙은? [ J',
    choices: [
      { id: 1, text: '자속변화에 의한 윤기기전력의' },
      { id: 2, text: '전자유도현상에 의하여 생기는' },
      { id: 3, text: '렌츠의 법칙' },
      { id: 4, text: '패러데이의 법칙' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p071',
    source: '2023.05 기출 #59',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '소방기본법령상 소방대장은 화재, 재난 • 재해 (그 밖의 위급한 상황3T1쟁한 현장에 소방활동 19.04, 문.42 구역을 정하여 소방활동에 필요한 자로서 대통 15.03.S43 I 령령으로 정하는 사람 외에는 그 구역에의 출입 쓰?으로쐬 을 제한할 수 있다. 다음 중 소방활동구역에 출 입할 수 없는 사람은?',
    choices: [
      { id: 1, text: '소방활동구역 안에 있는 소방대상물의 소유' },
      { id: 2, text: '전기 • 가스 • 수도 • 통신 • 교통의 업무에 종' },
      { id: 3, text: '소방업무의 응원요청을 받은 소방서장은 정당' },
      { id: 4, text: '의사 • 간호사 그 밖에 구조 • 구급업무에 종' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p072',
    source: '2023.09 기출 #1',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '•통기력이 좋지 않은 상태에서 연소 1 가 계속되어 산소가 심히 부족한 상 1 태가 되었을 때 개구부를 통하여 산 1 소가 공급되면 실내의 가연성 혼합기 가 공급되는 산소의 방향과 반대로 백드래프트 흐르며 급격히 연소하는 현상 (back draft) • 소방대가 소화활동을 위하여 화재실 의 문을 개방할 때 신선한 공기가 유 입되어 실내에 축적되었던 가연성 가 스가 단시간에 폭발적으로 연소함 으로써 화재가 폭풍을 동반하며 실외 로 분출되는 현상 ¥. 중요. 유에서 발생하는 현상 우 현“상 정 의 • 중질유의 석유탈크의서 장시간 조 용히 연소하다 텅三‘대의 잔존기름 이 갑자기 분출하현상 • 유류탱크에서 탱크바닥에 물과 기 름의 에멑셔의 섞여 있을 때 이로 보일오봐 인하여 화재가 발생하는 현상 (boil over) • 연소유면으로부터 100℃ 이상의 열 가 탱크 저부에 고여 있는 물을 비등하게 하면서 연소유를 탱크 밖 으로 비산시키며 연소하트 혁상 f wa 보저(보자기) j 20 I1 •저장탱크에 저장된 유류저장량이 1 오일오버 내용적의 50% 이하로 충전되어 있 06 (oil over) 을 때 화재로 인하여 탱크가 폭발하 는 현상 -------* • 물이 점성의 뜨거운 기름 표면 아래에 프로스오버 社厂으三— 1 ■ . 서 끓을 때 화재를 수반하지 않고 용기 (froth over) 가 넘치는 현상 • 물인 연소유의 뜨거운 표면에트•어 갈 때 기름 표면에서화재기7!쟁하 는 현상 •유호제로 소호하기 위한 물이 수분 슬롭오버 의 급격한 증발에 의하여 액면이 거 ^5^ over) 품을 일으키면서 열유층 밑의 냉유 가 급히 열팽창하여 기름의 일부가 불이 붙은 채 탱크벽을 넘어서 일출 하는 현상',
    choices: [
      { id: 1, text: '소방시설업자의 지위를 승계한 경우' },
      { id: 2, text: '소방시설업의 등록취소처분 또는 영업정지' },
      { id: 3, text: '휴업하거나 폐업한 경우' },
      { id: 4, text: '소방시설업의 주소지가 변경된 경우' },
    ],
    correctId: 4,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p073',
    source: '2023.09 기출 #44',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '소방시설 설치 및 관리에 관한 법령상 관리업자 기록하고 이를 해당 특정소방대상물에 부착하여 아니하거나 특정소방대상물의 출입자가 쉽게 볼 수 있는 장소에 게시하지 아니하였을 때 벌칙기 준은?',
    choices: [
      { id: 1, text: '100만원 이하의 과태료' },
      { id: 2, text: '200만원 이하의 과태료' },
      { id: 3, text: '300만원 이하의 과태료' },
      { id: 4, text: '500만원 이하의 과태료' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p074',
    source: '2023.09 기출 #47',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '화재의 예방 및 안전관리에 관한 법령상 소방대상 兩^ 뭄의 개수 - 이전 ■ 제거, 사용의 금지 또는 제한, 사용폐쇄, 공사의 정지 또는 중지, 그 밖의 필요한 조치로 인하여 손실을 받은 자가 손실보상청구서 에 첨부하여야 하는 서류로 틀린 것은?',
    choices: [
      { id: 1, text: '손실보상합의서' },
      { id: 2, text: '손실을 증명할 수 있는 사진' },
      { id: 3, text: '손실을 증명할 수 있는 증빙자료' },
      { id: 4, text: '소방대상물의 관계인임을 증명할 수 있는' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p075',
    source: '2023.09 기출 #66',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '무선통신보조설비의 증폭기에는 비상전원이 부 있는 것이어야 하는가?',
    choices: [
      { id: 1, text: '자가발전설비' },
      { id: 2, text: '축전지설비' },
      { id: 3, text: '전기저장장치' },
      { id: 4, text: '전기저장장치' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p076',
    source: '2024.05 기출 #48',
    difficulty: 2,
    subject: 3,
    subjectName: '소방관계법규',
    stem: '소방기본법에서 정의하는 용어에 대한 설명으로 F 호지틈린 것은? ©“소방대상물”이란 건축물, 차량, 핫해 중인 으 모든선박과 산림 그 밖의 인공구조물 또는 물건을 말한다.',
    choices: [
      { id: 1, text: '소방용수시설이 없는 지역' },
      { id: 2, text: '시장지역' },
      { id: 3, text: '목조건물이 밀집한 지역' },
      { id: 4, text: '“소방대장”이란 소방본부장 또는 소방서장 등' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p077',
    source: '2024.07 기출 #2',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '제어의 종류 종 류 설 명 • 일정한 목표값을 윤지하는 것으로 프로 세스제어, 자동조정이 이에 해당된다. 젗츠［제어 3 연속식 압연기 1 보기 （히 (fixed value • 목표값이 시간에 관계없이 항상 일정 control) 한 값을 가자는 제어이다. f GgO 유목정 ] ..........iiW-T기11\' ‘ ............ . 미지의 시간적 변화를 하는 목표값에 추종제어 제어량을 추종시키기 위한 제어로 서 (follow-up 보기구가 이에 해당된다. control) a 대공포의 포신 비율제어 둘 이상의 제어량을 소정의 비율로 제 (ratio control) 어하는 것이다. 목표값이 미리 적해진 시간저 보하르 프루그램젠어 하는 경우 제어량을 三것에 추종시키기 \' (program 위한 제어이다. control) a 열차 - 산업로봇의 무인운전 o스 제어량에 의한 분류 분 류 종 류 •온도 •압력 •豆량 •앺면 프로세스제어 서 GEEI 프온압유액',
    choices: [
      { id: 1, text: '불꽃감지기' },
      { id: 2, text: '이온화식 2종' },
      { id: 3, text: '차동식 분포형' },
      { id: 4, text: '보싹식 스포트형' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p078',
    source: '2025.02 기출 #8',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '연면적이 1000m2 이상인 건축물에 설치하는 방 화벽이 갖추어야 할 기준으로 틀린 것은?',
    choices: [
      { id: 1, text: '내화구조로서 홀로 설 수 있는 구조일 것' },
      { id: 2, text: '방화벽의 양쪽 끝과 위쪽 끝을 건축물의' },
      { id: 3, text: '방화벽에 설치하는 출입문의 너비 및 높' },
      { id: 4, text: '방화벽에 설치하는 출입문의 높이는 2.5m' },
    ],
    correctId: 2,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p079',
    source: '2025.02 기출 #80',
    difficulty: 3,
    subject: 4,
    subjectName: '소방전기시설',
    stem: '자동화재탐지설비 및 시각경보장치의 화재안전 石^] 기준에 따른 자동화재탐지설비의 중계기의 시설 기준으로 틀린 것은?',
    choices: [
      { id: 1, text: '조작 및 점검에 편리하고 화재 및 침수 등의' },
      { id: 2, text: '수신기에서 직접 감지기회로의 도통시험을' },
      { id: 3, text: '감지기 一 수신기, 누전경보기 一 과전류차단기' },
      { id: 4, text: '수신기에 따라 감시되지 아니하는 배선을' },
    ],
    correctId: 3,
    explanation: '',
    lawRef: '',
  },
  {
    id: 'p080',
    source: '2025.05 기출 #6',
    difficulty: 2,
    subject: 1,
    subjectName: '소방원론',
    stem: '폭굉（detonation）에 관한 설명으로 틀린 것은? 하연소속도가 음속보다 릴 때 나타난다. 3.09.문 13 2.04.문 13',
    choices: [
      { id: 1, text: '연소속도가 g속보다빠' },
      { id: 2, text: '온도의 상승은 충격' },
      { id: 3, text: '압력상승은 폭연의 경우보다 크다.' },
      { id: 4, text: '폭굉의 유도거리는 배관의 지름과 관계가' },
    ],
    correctId: 1,
    explanation: '',
    lawRef: '',
  },
]